{% set version = "1.3.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shades
  version: {{ version|replace("-", "_") }}

source:
  fn: shades_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/shades_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shades/shades_{{ version }}.tar.gz
  sha256: 96a083b47fc3519e1abed78f2114e4b918277909136ea2e6a1f1b978c63a6f61

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, covr
requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('shades')"           # [not win]
    - "\"%R%\" -e \"library('shades')\""  # [win]

about:
  home: https://github.com/jonclayden/shades
  license: BSD_3_clause + file LICENCE
  summary: Functions for easily manipulating colours, creating colour scales and calculating
    colour distances.
  license_family: BSD

extra:
  recipe-maintainers:
    - dpryan79
