appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: s3EJjWnb+lWaWrVokWPbmrSpsE/Y2Hyhm71ldTsmGqaiHaJHFzfNuEBw/NS3j7RL/ZLs5dhiBlAT2PUlsbZ5ara45iAYw4h87w9OrGoEozL9ynU5xNZY7csRm7NSNu10NewnPf9kOw83cVQidonKtNj416XKOvlHj4/rB/fVR5+A2ia6ZjCHeqxWEMS0t59iHZ2/ITRYTnSZG+rku9QE6SgDSC1aw5+1cISKz7x4mzZKCNSHMtKPN9S6RrhkL7qA7g72X3edvcMQyBZ25hphzyJmU/IQS0HWlkWuePEVO1G56dNj6eKMlBH5c52A64jNx4FtEeOr5twY7VROAUiwRd+Arc9gpDD601ntsoENLhi7CIJqRdtFVyh/SQ+f2skrKW/JYfsKv9G3HRX8pjODgFfwaU2CqiVLXB4Pnaoo0uR/TGHg1LOEVPDt7bHtSBo27NBWGp0r8cpdD0p9ynbirZ/9PqXPwwI3PdFoIj3iavuMfsXXYPWBQaov9QLkjQyEvRYli6nurWhjgrT21/IvxyHYB8hL+3sF7kOlMBDZTqvLzIWUkJKSzL4adeSUebPf1WTQfdmnG7JT2i/QVbvB/zTdFH9CemMX4N4S7qBZq2wrPSZIZMQihPY61/z894kdOkXCE1UZ6Zais31vB7zGVgsUUacqMNGo8NUHttRW9nM=}
